### ISSUE TITLE
celery 

### ISSUE THREAD

**Issue by DmitryZZZZZZ** [DmitryZZZZZZ/Portal#1]
[2023-05-02 17:26:27,448: WARNING/ForkPoolWorker-9] Message: 'Task %(name)s[%(id)s] %(description)s: %(exc)s'
Arguments: {'hostname': 'celery@MacBook-Air-Dmitrij.local', 'id': 'c2d73ee9-e59c-46ee-80ba-09ec806c817a', 'name': 'news.tasks.weekly_notification', 'exc': "SMTPRecipientsRefused({'1': (501, b'<1>: recipient address must contain a domain')})"

**Comment by DimHam163** [comment]
You have a problem in sending mail, try specifying a specific mail where to send it!

**Comment by DmitryZZZZZZ** [comment]
error accessing subscribers email field - 
corrected
